- templates/blocks/country_select.twig
[JIRA 4032](https://jira.greenpeace.org/browse/PLANET-4032)
[Related PR #185](https://github.com/greenpeace/planet4-plugin-engagingnetworks/pull/185)
> PLANET-4032 EN Form block - Rename placeholder text in Country field

- classes/blocks/class-enform.php
- templates/blocks/tease-thankyou.twig
[JIRA 4183](https://jira.greenpeace.org/browse/PLANET-4183)
> PLANET-4183 EN form - Use P4 setting donate text for donate button

- classes/class-loader.php
- classes/view/class-view.php
- templates/blocks/enform_post.twig
Load the editor scripts only enqueuing editor scripts while in context of the editor applied as well. 
[Ref](https://jira.greenpeace.org/browse/PLANET-4274)
> PLANET-4274 : EN settings fixes.

- classes/class-loader.php
[JIRA 4410](https://jira.greenpeace.org/browse/PLANET-4410)
eg. https://k8s.p4.greenpeace.org/sagardev/test-en-form-3/
> PLANET-4410 Fix EN dependency checkbox field issue

- assets/src/blocks/ENForm/ENForm.js
- Changed thank you page url label 
- added space above field
Ref: https://jira.greenpeace.org/browse/PLANET-4471
> PLANET-4471 EN form block: Rename fields

- assets/src/styles/blocks/ENForm/components/_enform-full-width-bg.scss
- assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
- templates/blocks/enform.twig
- Fixed alignment on en-form full and body width
- Fixed legal text font and size
Also contains changes for PLANET-4503.
Ref: https://jira.greenpeace.org/browse/PLANET-4431
Ref: https://jira.greenpeace.org/browse/PLANET-4503
> PLANET-4431 EN form block css is off

- classes/blocks/class-enform.php
[JIRA 4447](https://jira.greenpeace.org/browse/PLANET-4447)
> PLANET-4447 Escape og fields in EN form share buttons

- classes/class-loader.php
Issue spotted on [release site](https://release.k8s.p4.greenpeace.org/canada/wp-admin/post-new.php?post_type=page)
> Fix editor asset url

- assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
- assets/src/styles/blocks/ENForm/components/_enform.scss
Also fixed the size of checkbox that was off on one style.
> Adjust color of checkbox per EN style

- .githooks/prepare-commit-msg
- bin/copy-git-hooks.sh
- package.json
Ref: https://jira.greenpeace.org/browse/PLANET-4395
> PLANET-4395: Recreate Git hooks Gulp task in NPM

- admin/js/enforms.js
- classes/controller/class-ensapi-controller.php
- templates/blocks/enform_post.twig
- templates/blocks/position_select.twig
- templates/selected_enform_fields.twig
Rebase the branch and squash commits into one.
> PLANET-4240 - EN form add 'position' dropdown field

- .circleci/config.yml
- .gitignore
- assets/src/styles/components/FormHelp.scss
- assets/src/styles/components/FormSectionTitle.scss
- assets/src/styles/components/InlineFormFeedback.scss
- assets/src/styles/components/ValidationMessage.scss
- classes/blocks/class-base-block.php
- classes/blocks/class-enform.php
- classes/class-loader.php
- classes/controller/api/class-rest-controller.php
- classes/controller/class-enform-fields-list-table.php
- classes/controller/class-enform-questions-list-table.php
- classes/controller/class-ensapi-controller.php
- classes/controller/menu/class-controller.php
- classes/controller/menu/class-enform-post-controller.php
- classes/controller/menu/class-settings-controller.php
- classes/view/class-view.php
- composer.json
- composer.lock
- loco.xml
- phpcs.xml
- tests/bootstrap.php
Fix unit tests docker to point to docker hub.
Clean up .gititnore and removed OS and IDE specific files. These should live in local exclusion config.
Update composer dependencies. WP Coding Standards 2.2 are throwing an error for Short Syntax Arrays, but since we use everywhere added a phpcs config to exclude it and instead raise an error for Long Syntax.
Fixed l10n textdomain on phpcs configuration.
Fixed scss code that was failing stylelint.
> Add CI configuration for running tests

- .circleci/config.yml
- .gitignore
- assets/src/styles/components/FormHelp.scss
- assets/src/styles/components/FormSectionTitle.scss
- assets/src/styles/components/InlineFormFeedback.scss
- assets/src/styles/components/ValidationMessage.scss
- classes/blocks/class-base-block.php
- classes/blocks/class-enform.php
- classes/class-loader.php
- classes/controller/api/class-rest-controller.php
- classes/controller/class-enform-fields-list-table.php
- classes/controller/class-enform-questions-list-table.php
- classes/controller/class-ensapi-controller.php
- classes/controller/menu/class-controller.php
- classes/controller/menu/class-enform-post-controller.php
- classes/controller/menu/class-settings-controller.php
- classes/view/class-view.php
- composer.json
- composer.lock
- loco.xml
- phpcs.xml
- tests/bootstrap.php
[JIRA 4510](https://jira.greenpeace.org/browse/PLANET-4510)
Fixed PHP notices -
`Notice: Trying to get property 'ID' of non-object in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-engagingnetworks/classes/blocks/class-enform.php on line 226
Notice: Trying to get property 'ID' of non-object in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-engagingnetworks/classes/blocks/class-enform.php on line 227
Notice: Trying to get property 'ID' of non-object in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-engagingnetworks/classes/blocks/class-enform.php on line 228`
`Notice: Trying to get property 'ID' of non-object in /app/source/public/wp-content/plugins/planet4-plugin-gutenberg-engagingnetworks/classes/blocks/class-enform.php on line 237` …
> PLANET-4510 Fix PHP notices

- templates/blocks/enform_post.twig
Ref: https://jira.greenpeace.org/browse/PLANET-4331
> PLANET-4331: #403329: EN Form: EN Type GEN label appears twice

- assets/src/styles/blocks/ENForm/components/_enform.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4075
Added responsive styling to full width Thank you pages
> PLANET-4075 Thank you screen not responsive for "Page body-text" and "Full page width" styles

- classes/class-loader.php
[JIRA 4768](https://jira.greenpeace.org/browse/PLANET-4768)
> PLANET-4768 Fix En form 'posts_per_page' value in P4 EN form dropdown

- assets/src/styles/blocks/ENForm/campaigns/_mixins.scss
- removed scss that removes padding from bottom of EN-Block
Ref: https://jira.greenpeace.org/browse/PLANET-4846
> PLANET-4846 Planet 4 Bug Report: EN Form: Bottom vertical space is off

- assets/src/blocks/ENForm/ENForm.js
- Added URL HTTPS validation for custom URLS
> PLANET-4143 All blocks: Add https:// validation error for url fields

- assets/src/styles/blocks/ENForm/components/_enform.scss
- Implemented flex for the social buttons
> PLANET-5025 Social buttons not aligned on Thank You Form

- assets/src/styles/blocks/ENForm/components/_enform.scss
Just changing some grey shades.
Ref: https://jira.greenpeace.org/browse/PLANET-5082
Related PRs:
https://github.com/greenpeace/planet4-master-theme/pull/1128
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/312
https://github.com/greenpeace/planet4-styleguide/pull/64
> PLANET-5082: Accessibility change red based greys to blue based ones.
